# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese nombre del proyecto', max_length=200, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TodoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.TextField(help_text='Descripci\xf3n de la tarea', verbose_name='Tareas')),
                ('fecha', models.DateField()),
                ('fktodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo')),
            ],
            options={
                'verbose_name': 'Todo Tarea',
                'verbose_name_plural': 'Todo Tareas',
            },
        ),
    ]
